notes/urls.py
from django.urls import path

from .views import (
    CreateNoteView,
    ReadNotesView,
    UpdateNoteView,
    DeleteNoteView,
    mark_note_view,
)

urlpatterns = [
    path('read/', ReadNotesView.as_view(), name='read_notes'),
    path('create/', CreateNoteView.as_view(), name='create_note'),
    path('delete/<int:pk>/', DeleteNoteView.as_view(), name='delete_note'),
    path('edit/<int:pk>/', UpdateNoteView.as_view(), name='edit_note'),
    path('mark/<pk>/', mark_note_view, name='mark_note'),
]

notes_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from notes.views import HomePageView

from django_email_verification import urls as email_urls 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='homepage'),
    path('auth/', include('authenticate.urls')),
    path('notes/', include('notes.urls')),
    path('notes/', include('collections_module.urls')),
    path('email/', include(email_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/models.py
from collections_module.models import Collection
from django.db import models
from django.conf import settings
from datetime import datetime
import datetime

# Create your models here.

User = settings.AUTH_USER_MODEL
    
class Note(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    collection = models.ForeignKey(Collection, null=True, on_delete=models.SET_NULL)
    header = models.CharField(max_length = 30)
    date = models.DateTimeField(default=datetime.date.today)
    text = models.TextField(max_length = 350)
    is_important = models.BooleanField(null=True, default=False)

    class Meta:
        ordering = ['-is_important', '-date']

    def __str__(self):
        return self.header

notes/forms.py
from django import forms

from .models import Note

class CreateNoteModelForm(forms.ModelForm):

    class Meta:
        model = Note
        fields = [
            'header',
            'text',
        ]
        widgets = {
            'header': forms.TextInput(attrs={'placeholder': 'Note header'}),
        }

notes/views.py
import math
from multiprocessing import context

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin

from django.views.generic import (
                                  CreateView,
                                  ListView,
                                  UpdateView,
                                  DeleteView,
                                    )
from .models import Note
from collections_module.models import Collection
from authenticate.models import UserInfo
from .forms import CreateNoteModelForm
from .models import Note

class HomePageView(View):
    template_name = 'index.html'

    def get(self, request, *args, **kwargs):
        user = request.user
        return render(request, 'index.html', {'profile': user})

class CreateNoteView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Note
    form_class = CreateNoteModelForm
    template_name = 'notes/create_note.html'
    success_url = reverse_lazy('read_notes')
    success_message = "Your note has been successfully created!"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = self.request.user
        context['user_info'] = get_object_or_404(UserInfo, user=self.request.user)
        return context

class UpdateNoteView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Note
    form_class = CreateNoteModelForm
    template_name = 'notes/edit_note.html'
    success_message = 'Your note was successfully updated!'
    success_url = reverse_lazy('read_notes')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['note'] = get_object_or_404(Note, pk=self.kwargs['pk'])
        context['user_info'] = get_object_or_404(UserInfo, user=self.request.user)
        return context

class DeleteNoteView(LoginRequiredMixin, DeleteView):
    model = Note
    template_name = 'notes/delete_note.html'
    success_url = reverse_lazy('read_notes')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['notes'] = Note.objects.all()
        context['note'] = get_object_or_404(Note, pk=self.kwargs['pk'])
        context['user_info'] = get_object_or_404(UserInfo, user=self.request.user)
        context['pk'] = self.kwargs['pk']
        return context
        
class ReadNotesView(LoginRequiredMixin, ListView):
    template_name = 'notes/read_notes.html'
    paginate_by = 6
    context_object_name = 'notes'
        
    def get(self, request, *args, **kwargs):
        page = int(request.GET.get('page', 1))

        selected_collection = int(request.GET.get('collection', 0))
        add_mode_collection = int(request.GET.get('add_mode_collection', 0)) # id коллекции, если пользователь добавляет к ней заметки

        if selected_collection:
            notes = Note.objects.filter(user=request.user, collection=selected_collection)
        elif add_mode_collection:
            notes = Note.objects.filter(user=request.user, collection=None)
        else:
            notes = Note.objects.filter(user=request.user)

        search_input = self.request.GET.get('search-input', '')
        s = False
        notes_count = Note.objects.all().count()
        if search_input:
            s = True
            notes = Note.objects.filter(header__icontains=search_input)
            notes_count = Note.objects.filter(header__icontains=search_input).all().count()
            if not notes:
                s = False
                messages.error(request, 'Notes Not Found!')
                return redirect('read_notes')


        collections = Collection.objects.filter(user=request.user)
        user_info = get_object_or_404(UserInfo, user=request.user)
        start_index = (page * self.paginate_by) - self.paginate_by
        end_index = page * self.paginate_by
        pages_count = math.ceil(len(notes) / self.paginate_by)

        if notes:
            notes_list = notes[start_index:end_index]
        else:
            notes_list = []

        return render(request, 'notes/read_notes.html', {
                                                         'notes_list': notes_list,
                                                         'collections': collections,
                                                         'current_page': page,
                                                         'next': page + 1,
                                                         'prev': page - 1,
                                                         'pages_count': pages_count,
                                                         'pages_count_list': range(1, pages_count+1),
                                                         'add_mode_collection': add_mode_collection,
                                                         'search_input': search_input,
                                                         'selected_collection': selected_collection,
                                                         'user_info': user_info,
                                                         'notes_count': notes_count,
                                                         's': s
                                                         })
    

def mark_note_view(request, pk):
    note = get_object_or_404(Note, id=pk)
    note.is_important = not note.is_important
    note.save()

    return redirect('read_notes')

templates/notes/create_note.html
    <div class="section-create">
        <div class="section-create-wrapper">
            {% if messages %}
            <div class="messages {{user_info.theme}}_m">
                <div class="top">
                    <button class="cross {{ user_info.theme }}_c"></button>
                </div>
                <div class="bottom">
                    <div class="blockfirst">
                        <div class="correct"></div>
                    </div>
                    <div class="blocksecond">
                        {% for message in messages %}
                        <h1 {% if message.tags %} class="{{ message.tags }} {{ user_info.theme }}_mtext"{% endif %}>{{ message }}!</h1>
                        {% endfor %}
                        <a class="linktoread {{ user_info.accent_color }}_linkw" href="/notes/read/">Watch it!</a>
                    </div>
                </div>
            </div>
            {% endif %}
            <div class="section-create-wrapper__main">
                <div class="section-create-wrapper__main__box {{ user_info.theme }}_bgbox">
                    <div class="section-create-wrapper__main__box__image"></div>
                    <div class="block_createform">
                        <h1 class="create_text {{user_info.theme}}_colortext">Create Note</h1>
                        <form class="creation" action="/notes/create/" method="post" autocomplete="off">
                            {% csrf_token %}
                        
                            <p>
                                <label class="headertext {{user_info.theme}}_labeltext" for="id_header">Note header:</label>
                                {{ form.header }}
                            </p>
                            <p>
                                <label class="bodytext {{user_info.theme}}_labeltext" for="id_text">Note text:</label>
                                {{ form.text }}
                            </p>
                            <button class="submit {{user_info.accent_color}}_btn" type="submit">Create note</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
<script>

    // name
    document.getElementById("id_header").classList.add("header_field_{{user_info.accent_color}}");

    // text
    document.getElementById("id_text").classList.add("text_field_{{user_info.accent_color}}");
    document.getElementById("id_text").placeholder = "Note text";
    
    let cross = document.querySelector('.cross');
    let messages = document.querySelector('.messages');
    cross.addEventListener("click", (e) => {
        messages.classList.toggle('remove')
    })
    let create = document.querySelector('.create-block');
    let sectionCreate = document.querySelector('.section-create');

    create.addEventListener("click", (e) => {
        sectionCreate.style.display = 'block'
    });
</script>

templates/notes/delete_note.html
<section class="section-delete">
    <div class="section-delete-wrapper">
        <div class="section-delete-wrapper__box {{user_info.theme}}_bg">
            <form class="delete" action="/notes/delete/{{pk}}/" method="post">
                {% csrf_token %}
                <p class="text {{user_info.theme}}_elems">Are you sure to delete note <span class='{{user_info.theme}}_elems'>"{{ note.header }}"</span>?</p>
                <button class="submit {{user_info.accent_color}}_bg" type="submit">Delete Note</button>
            </form>
        </div>
    </div>
</section>

templates/notes/edit_note.html
<section class="section-update">
    <div class="section-update-wrapper">
        {% if messages %}
        <div class="edit_messages">
            <div class="top">
                <button class="cross"></button>
            </div>
            <div class="bottom">
                {% for message in messages %}
                <h1 {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}! <a class="linktoread" href="/notes/read/">Go to your notes and check your updated note up</a></h1>
                {% endfor %}
            </div>
        </div>
        {% endif %}
        <div class="section-update-wrapper__main">
            <div class="section-update-wrapper__main__box {{ user_info.theme }}_bgbox" >
                <form class="form_upd" action="/notes/edit/{{ pk }}/" method="post">
                    <h1 class="update_text {{user_info.theme}}_colortext">Update Note</h1>
                    {% csrf_token %}
                    
                    <h4 class="edit_header_text {{user_info.theme}}_labeltext">Edit note header:</h4>
                    {{ form.header }}

                    <h4 class="edit_body_text {{user_info.theme}}_labeltext">Edit note text:</h4>
                    {{ form.text }}
            
                    <button class="submit {{user_info.accent_color}}_btn" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
</section>
<script>
    // name
    document.getElementById("id_header").classList.add("header_upd_field_{{user_info.accent_color}}");
    document.getElementById("id_header").placeholder = "Updated header";

    // text
    document.getElementById("id_text").classList.add("text_upd_field_{{user_info.accent_color}}");
    document.getElementById("id_text").placeholder = "Updated text";

    let cross = document.querySelector('.cross');
    let edit_messages = document.querySelector('.edit_messages');
    cross.addEventListener("click", (e) => {
        edit_messages.classList.toggle('remove')
    })
</script>